matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      services:
        - docker
      cache:
        directories:
          - ./client/web/node_modules
      before_install:
      - (cd client/web && docker-compose up -d)
      script:
        - docker exec web /bin/sh -c "npm run test:ci"
        - if [ "$TRAVIS_BRANCH" = "master" ]; then docker exec web /bin/sh -c "npm run build_prod"; fi
        - if [ "$TRAVIS_BRANCH" = "develop" ]; then docker exec web /bin/sh -c "npm run build_dev"; fi
      after_script:
      - docker-compose down      
      deploy:
        - provider: surge
          skip_cleanup: true
          domain: schedule-me-up_dev.surge.sh
          project: ./client/web/build/
          on:
            branch: dev
        - provider: surge
          skip_cleanup: true
          domain: schedule-me-up.surge.sh
          project: ./client/web/build/
          on:
            branch: master
#    - language: android
#      dist: trusty
#      android:
#        components:
#          # Uncomment the lines below if you want to
#          # use the latest revision of Android SDK Tools
#          # - tools
#          # - platform-tools
#      
#          # The BuildTools version used by your project
#          - build-tools-26.0.2
#      
#          # The SDK version used to compile your project
#          - android-26
#      
#          # Additional components
#          - extra-google-google_play_services
#          - extra-google-m2repository
#          - extra-android-m2repository
#      
#          # Specify at least one system image,
#          # if you need to run emulator(s) during your tests
#          - sys-img-x86-android-26
#          - sys-img-armeabi-v7a-android-17
