matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      services:
        - docker
        - mysql
      cache:
        directories:
          - ./client/web/node_modules
          - ./server/node_modules
      before_install:
        - (cd client/web && travis_wait docker-compose up -d)
      before_script:
        - (cd server && npm install)
        - (cd client/mobile && npm install)
      script:
        - (cd server && npm test && npx eslint ./)
        - (cd client/mobile && npm run test:ci && npm run lint)
        - docker exec web /bin/sh -c "eslint src"
        - docker exec web /bin/sh -c "npm run test:ci"
        - if [ "$TRAVIS_BRANCH" = "master" ]; then docker exec web /bin/sh -c "npm run build_prod && mv build/index.html build/200.html"; fi
        - if [ "$TRAVIS_BRANCH" = "develop" ]; then docker exec web /bin/sh -c "npm run build_dev && mv build/index.html build/200.html"; fi
      after_script:
        - (cd client/web && travis_wait docker-compose down)      
      deploy:
        - provider: surge
          skip_cleanup: true
          domain: schedule-me-up-dev.surge.sh
          project: ./client/web/build/
          on:
            branch: develop
        - provider: surge
          skip_cleanup: true
          domain: schedule-me-up.surge.sh
          project: ./client/web/build/
          on:
            branch: master
        - provider: elasticbeanstalk
          access_key_id:
            secure: $EBS_ACCESS_KEY
          secret_access_key:
            secure: '$EBS_SECRET_KEY'
          region: "us-east-2"
          app: "schedule-me-up"
          env: "schedule-me-up-dev"
          bucket_name: "elasticbeanstalk-us-east-2-508404004676"
          skip_cleanup: true
          on:
            branch: aws-hotfix
        - provider: elasticbeanstalk
          access_key_id:
            secure: $EBS_ACCESS_KEY
          secret_access_key:
            secure: '$EBS_SECRET_KEY'
          region: "us-east-2"
          app: "schedule-me-up"
          env: "schedule-me-up-prod"
          bucket_name: "elasticbeanstalk-us-east-2-508404004676"
          skip_cleanup: true
          on:
            branch: master
