matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      services:
        - docker
        - mysql
      cache:
        directories:
          - ./client/web/node_modules
          - ./server/node_modules
      before_install:
        - (cd client/web && travis_wait docker-compose up -d)
        - docker exec web /bin/sh -c "npm install"
      before_script:
        - (cd server && npm install)
      script:
        - (cd server && npm test && npx eslint ./)
        - docker exec web /bin/sh -c "eslint src"
        - docker exec web /bin/sh -c "npm run test:ci"
        - if [ "$TRAVIS_BRANCH" = "master" ]; then docker exec web /bin/sh -c "npm run build_prod"; fi
        - if [ "$TRAVIS_BRANCH" = "develop" ]; then docker exec web /bin/sh -c "npm run build_dev"; fi
      after_script:
        - (cd client/web && travis_wait docker-compose down)      
      deploy:
        - provider: surge
          skip_cleanup: true
          domain: schedule-me-up_dev.surge.sh
          project: ./client/web/build/
          on:
            branch: develop
        - provider: surge
          skip_cleanup: true
          domain: schedule-me-up.surge.sh
          project: ./client/web/build/
          on:
            branch: master
        - provider: elasticbeanstalk
          access_key_id:
            secure: $EBS_ACCESS_KEY
          secret_access_key:
            secure: '$EBS_SECRET_KEY'
          region: "us-east-2"
          app: "schedule-me-up"
          env: "schedule-me-up-dev"
          bucket_name: "elasticbeanstalk-us-east-2-508404004676"
          skip_cleanup: true
          on:
            branch: develop
        - provider: elasticbeanstalk
          access_key_id:
            secure: $EBS_ACCESS_KEY
          secret_access_key:
            secure: '$EBS_SECRET_KEY'
          region: "us-east-2"
          app: "schedule-me-up"
          env: "schedule-me-up-prod"
          bucket_name: "elasticbeanstalk-us-east-2-508404004676"
          skip_cleanup: true
          on:
            branch: master
#    - language: android
#      dist: trusty
#      android:
#        components:
#          # Uncomment the lines below if you want to
#          # use the latest revision of Android SDK Tools
#          # - tools
#          # - platform-tools
#      
#          # The BuildTools version used by your project
#          - build-tools-26.0.2
#      
#          # The SDK version used to compile your project
#          - android-26
#      
#          # Additional components
#          - extra-google-google_play_services
#          - extra-google-m2repository
#          - extra-android-m2repository
#      
#          # Specify at least one system image,
#          # if you need to run emulator(s) during your tests
#          - sys-img-x86-android-26
#          - sys-img-armeabi-v7a-android-17
